version: '3'
services: 
     jenkins:
        image: jenkins
        ports:
          - 8089:8080
          - 50000:50000
        volumes:
           - jenkins_home:/home/jenkins_home

volumes:
      jenkins_home:


